name: Deploy Lambda Function

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -name: Checkout code
     uses: actions/checkout@v2

     -name: Setup up Node.js
     uses: actions/setup-node@v2
     with:
      node-version: '20'

    -name: Setup up Go
     uses: actions/setup-go@v2
     with:
      go-version: '1.20'
    
    -name: Install dependencies
     run: npm install
     working-directory: ./cdk-hello-world

    -name: Build Lambda
     run: | 
        GOOS=linux GOARCH=amd64 go build -o main main.go
        cp main bootstreap
        zip function.zip bootstrap
     working-directory: ./hello-world

    -name: CDK Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRETS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: npx cdk deploy --require-approval never
      working-directory: ./cdk-hello-world